### ISSUE TITLE
property "height" freezes the browser

### ISSUE THREAD

**Issue by Fire-Brand** [RickStrahl/jquery-watch#5]
Hi, Thanks alot for the plugin! very helpufl!

I'm having a problem when i add the "height" property to the watched properties, chrome and FireFox just get stuck while loading the page, any idea why? 
here is my code:
```javascript
    var elem2watch = $j('.myClass');
    
    elem2watch.watch({
        properties: "display,height",
    
        callback: function(data, i) {
            var propChanged = data.props[i];
            var newValue = data.vals[i];
    
            var elem2watch = this;
            var elem2watch$j = $j(this);
    
            // do what you need based on changes
            // or do your own checks
            // console.log('elem2watch :',elem2watch);
            // console.log('data :',data);
            // console.log('i :',i);
            console.log('changed css');
            
            if( ($j(elem2watch).css('display') === "block") )
            {
              // some more code that works if "height" is not included to the watched prop
            }
        }
    });
```

**Comment by RickStrahl** [comment]
Sorry I didn't attend to this.

I gave this try in 1.20.0. I change the sample to be resizable, and resizing the height.

I added the resizable:

```javascript
  el.draggable().closable().resizable();
```

and then also added `height` to the monitored properties:

```javascript
        // Hook up CSS and Class watch operation
        el.watch({
            properties: "top,left,height,opacity,display,attr_class",
            callback: watchShadow
        });
```

I didn't see any issues when resizing the left box. The right box resizes right along with the left and mirroring. I don't see any slow downs or delay.

Keep in mind that you'll want to be quick about whatever you are doing in response to those events because there could be quite a lot of them firing in very quick order and that can have adverse affects on performance. One trick might be to use setTimeout() for the longer operations or use a debounce() routine to slow down the event firing.
