### ISSUE TITLE
Multiple watchers on same div not triggering each callback

### ISSUE THREAD

**Issue by tibineagu** [RickStrahl/jquery-watch#6]
First off - amazing plugin! Really hits the nail on the head for a lot of us out here.

I've just started using it and noticed that if you add more than one watcher on the same element, only the first callback will be called.

Maybe I'm doing something wrong or is this a limitation of the Mutation API?

Thanks!

**Comment by adamck** [comment]
I've run into this as well.

Gotta echo that praise above -- great plugin!

**Comment by RickStrahl** [comment]
Can you give me a use case where you see this behavior and where it matters. Basically you'll see change event firing for every change, but if there are multiple changes in the DOM event turn you will only get a single event. You still have to check what's changed anyway and you get all the changed elements in one pass.

I guess I'm not sure where this would be necessary since you can run through all properties on your own.

**Comment by RickStrahl** [comment]
On a side note: I flagged this as a bug but I don't remember my thought process actually :-) I think I wrote a response here but didn't actually submit it. Grrr...

**Comment by tibineagu** [comment]
@RickStrahl it's been a while since I opened this and I found a work-around, but I think this is one use case that I've personally experienced:

```javascript
// Custom object
function MyObject(elementID) {
    $('#' + elementID).watch(function() {
        // ...
    }

    return this;
}

var myObject1 = new MyObject('testDiv');
var myObject2 = new MyObject('testDiv');
```

Instances of `MyObject` will depend on detecting changes in their `elementID`. In the case described above, it's the same div for both instances, but only `myObject1` will get the event triggered.

**Comment by RickStrahl** [comment]
Oh I see. If you have more than one watcher you have to assign an ID to the watcher.

You can actually solve that problem by giving your watch a unique id.  By default the watcher uses iususes `_watcher` as the id but you can override that to anything you know. 

Maybe you could do something like this:

```javascript
function MyObject(elementID) {
    var uniqueId = "_watcher_" + new Date().getTime();
    $('#' + elementID).watch({
        // ...
        id: uniqueId,
        callback: function() {
            // ...
        }
    });
    return this;
}
```

**Comment by RickStrahl** [comment]
This has now been fixed in that the default ID assigned is unique (in version 1.16). You can still override the behavior and assign your own id so you can track the watcher as before, but the default behavior now gives unique watcher ids so if you attach multiple watchers to the same selector you get separate notifications.
